### ISSUE TITLE
Crash with Diseases Expanded

### ISSUE THREAD

**Issue by SteveS8** [pether-pg/ONI_Mods_byPether#24] opened 2022-03-10 13:03 UTC
Getting this:

Error in GameAssets(Clone).Assets.OnPrefabInit 
System.MissingMethodException: void Klei.AI.Disease..ctor(string,byte,Klei.AI.Disease/RangeInfo,Klei.AI.Disease/RangeInfo,Klei.AI.Disease/RangeInfo,Klei.AI.Disease/RangeInfo,bool)
  at DiseasesExpanded.DiseasesExpanded_Patches_AllCommon+Diseases_Constructor_Patch.Postfix (Database.Diseases& __instance, System.Boolean statsOnly) [0x00000] in <ae46ac16d11446ce9c229f8bcd71ec1a>:0 
  at (wrapper dynamic-method) Database.Diseases.Database.Diseases..ctor_Patch2(Database.Diseases,ResourceSet,bool)
  at (wrapper dynamic-method) Db.Db.Initialize_Patch2(Db)
  at Db.Get () [0x0001c] in <33cbadb4d53344698461e1b8bda03e57>:0 
  at Assets.CreatePrefabs () [0x00000] in <33cbadb4d53344698461e1b8bda03e57>:0 
  at Assets.OnPrefabInit () [0x0027f] in <33cbadb4d53344698461e1b8bda03e57>:0 
  at KMonoBehaviour.InitializeComponent () [0x00068] in <53ba8544b0394db88dcaac034e1fe553>:0 

  at UnityEngine.Debug.LogError (System.Object message, UnityEngine.Object context) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at Debug.LogError (System.Object obj, UnityEngine.Object context) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at DebugUtil.LogErrorArgs (UnityEngine.Object context, System.Object[] objs) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at DebugUtil.LogException (UnityEngine.Object context, System.String errorMessage, System.Exception e) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at KMonoBehaviour.InitializeComponent () [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at KMonoBehaviour.Awake () [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent_Injected (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3& pos, UnityEngine.Quaternion& rot) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.GameObject parent, System.String name, System.Boolean initialize_id, System.Int32 gameLayer) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.GameObject parent, System.String name) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at LaunchInitializer.Update () [0x00000] in <33cbadb4d53344698461e1b8bda03e57>:0 
Build: U41-498381-S

**Comment by pether-pg** [comment] 2022-03-16 11:51
Hi.
Thanks for the report. Sadly, I cannot reproduce this issue. It looks similar to issue I fixed some time ago. Could you please:
1. Make sure you have all mods up to date (steam sometimes does not update correctly, use "Mod Updater" mod by Stephen to force update)
2. Provide full Player.log file
3. Provide step-by-step reproduction instruction

Thanks a lot!

**Comment by SteveS8** [comment] 2022-03-16 16:50
I use the mod manager and that should have kept the mod up to date too. 

In any case, today's update seems to fixed it. It happened when just loading the game with the mod activated. Now that works.

**Comment by pether-pg** [comment] 2022-03-16 17:04
I saw many bad comments about Mod Manager and suggestions to use Mod Updater instead. Cannot tell if those valid since I use Updater only, but if you had issues with Managers you might want to consider Updater instead.

Anyway, I'm glad it seems fixed now (today's update had nothing to do with it though). I'm closing the issue, please let me know if that one reappears or you see something else wrong with the mod

**Closed by pether-pg** 2022-03-16 17:04 UTC
