### ISSUE TITLE
Irregular crashing since August 2nd update

### ISSUE THREAD

**Issue by EnsorcelledCat** [pether-pg/ONI_Mods_byPether#31] opened 2022-08-06 07:47 UTC
I know there's nothing a developer hates to hear more than a non-specified crash; I've tried, but I haven't been able to isolate the conditions that cause it. Other than that it seems to happen more often with the game paused. The crash log has looked similar every time. It's attached.

[Crash Log ONI 08-06-2022.txt](https://github.com/pether-pg/ONI_Mods_byPether/files/9274622/Crash.Log.ONI.08-06-2022.txt)

Thanks for all your work on the mod. It really is wonderful when it's working.

**Comment by EnsorcelledCat** [comment] 2022-08-06 07:55
I should also mention that I saw a similar entry in the crash log from someone using Diseases Restored/Reimagined. I don't use that mod, but I do use Decor Reimagined from the same author. Maybe that?

**Comment by pether-pg** [comment] 2022-08-07 20:10
That looks very strange. The crash is because the game tries to get a color assigned to some room, but the color is not there and everything goes black hole. That would make some sense at the beginning of the game if somebody didn't add correct color, but if you open room overlay once and it is OK it means all colors are there, and the crash should never happen in the future.

My guess is that this is some random base game bug, but I will keep the issue open and investigate - maybe there is something wrong with the mods

**Comment by pether-pg** [comment] 2022-08-21 16:40
I couldn't reproduce the issue, but I modified some code to mitigate it and potentially fix.
Please check if the issue remains at version 2022.8.21.1610
I will close the issue as fixed, but if you encounter it again, please let me know!
Thanks!

**Closed by pether-pg** 2022-08-21 16:40 UTC
