### ISSUE TITLE
Game crash after new update

### ISSUE THREAD

**Issue by kritsananac** [pether-pg/ONI_Mods_byPether#37] opened 2022-10-12 09:43 UTC
```
Exception while loading mod pether-pg.RoomsExpanded at C:/Users/USER/Documents/Klei/OxygenNotIncluded/mods/Steam/2348079481. 
HarmonyLib.HarmonyException: Patching exception in method null ---> System.ArgumentException: Undefined target method for patch method static System.Void RoomsExpanded.RoomType_Constructor_Patch::Prefix(System.String id, RoomType[]& upgrade_paths)
  at HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) [0x00047] in <2f5aaaa000594d07b9998f4cff1e9662>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x00057] in <2f5aaaa000594d07b9998f4cff1e9662>:0 
   --- End of inner exception stack trace ---
  at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x00127] in <2f5aaaa000594d07b9998f4cff1e9662>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x00082] in <2f5aaaa000594d07b9998f4cff1e9662>:0 
  at HarmonyLib.Harmony.<PatchAll>b__10_0 (System.Type type) [0x00007] in <2f5aaaa000594d07b9998f4cff1e9662>:0 
  at HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <2f5aaaa000594d07b9998f4cff1e9662>:0 
  at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00006] in <2f5aaaa000594d07b9998f4cff1e9662>:0 
  at KMod.UserMod2.OnLoad (HarmonyLib.Harmony harmony) [0x00007] in <cb20703507b14eea8088dbc44abf7f85>:0 
  at RoomsExpanded.ModInfo.OnLoad (HarmonyLib.Harmony harmony) [0x00000] in <5bd329b3adff46fc99c794ab8f424a80>:0 
  at KMod.DLLLoader.LoadDLLs (KMod.Mod ownerMod, System.String harmonyId, System.String path, System.Boolean isDev) [0x00222] in <cb20703507b14eea8088dbc44abf7f85>:0 

  at UnityEngine.Debug.LogError (System.Object message, UnityEngine.Object context) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Debug.LogError (System.Object obj, UnityEngine.Object context) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at DebugUtil.LogErrorArgs (UnityEngine.Object context, System.Object[] objs) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at DebugUtil.LogException (UnityEngine.Object context, System.String errorMessage, System.Exception e) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at KMod.DLLLoader.LoadDLLs (KMod.Mod ownerMod, System.String harmonyId, System.String path, System.Boolean isDev) [0x00000] in <cb20703507b14eea8088dbc44abf7f85>:0 
  at KMod.Mod.Load (KMod.Content content) [0x00000] in <cb20703507b14eea8088dbc44abf7f85>:0 
  at KMod.Manager.Load (KMod.Content content) [0x00000] in <cb20703507b14eea8088dbc44abf7f85>:0 
  at Global.Awake () [0x00000] in <cb20703507b14eea8088dbc44abf7f85>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent_Injected (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3& pos, UnityEngine.Quaternion& rot) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.GameObject parent, System.String name, System.Boolean initialize_id, System.Int32 gameLayer) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.GameObject parent, System.String name) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at LaunchInitializer.Update () [0x00000] in <cb20703507b14eea8088dbc44abf7f85>:0 
Build: U43-526233-S
```

**Comment by pether-pg** [comment] 2022-10-12 21:10
Duplicate of https://github.com/pether-pg/ONI_Mods_byPether/issues/36
Please make sure you have most recent version of the mod

**Closed by pether-pg** 2022-10-12 21:10 UTC
