### ISSUE TITLE
Rooms Expanded: Crash on game startup, after update

### ISSUE THREAD

**Issue by ezonius** [pether-pg/ONI_Mods_byPether#30] opened 2022-08-01 04:57 UTC
Not sure why it can't iterate over it, I can open the path to the file just fine outside the game.

```
Cannot iterate over $D:/Libraries/Documents/Klei/OxygenNotIncluded/mods/Steam/2348079481/archived_versions/2021.zip, this directory does not exist

  at UnityEngine.Debug.LogError (System.Object message) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Debug.LogError (System.Object obj) [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at KMod.Directory.GetTopLevelItems (System.Collections.Generic.List`1[T] file_system_items, System.String relative_root) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at KMod.Mod.GetModInfoForFolder (System.String relative_root) [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at KMod.Mod.GetMostSuitableArchive () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at KMod.Mod.ScanContent () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at KMod.Manager.LoadModDBAndInitialize () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at Global.Awake () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent_Injected (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3& pos, UnityEngine.Quaternion& rot) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.GameObject parent, System.String name, System.Boolean initialize_id, System.Int32 gameLayer) [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.GameObject parent, System.String name) [0x00000] in <8c239b169b544cce8b8bc7ddd2d09e10>:0 
  at LaunchInitializer.Update () [0x00000] in <1c7e9ccb4aa844e2be4538990aabf98e>:0 
Build: U42-514967-S
```

**Comment by ezonius** [comment] 2022-08-01 05:07
I have to completely remove the mod to start up the game. Even having it inactive will crash the game.

**Comment by ezonius** [comment] 2022-08-01 05:09
Reinstalling the mod (unsub -> sub) will cause it to crash again.

**Comment by pether-pg** [comment] 2022-08-01 06:12
the issue is now fixed, please update your mod to the newest release
removing conflicting .zip file will also mitigate the issue

**Closed by pether-pg** 2022-08-01 06:12 UTC
